### 게시글 목록 조회
GET http://localhost:8080/api/posts

### 게시글 정보 생성 성공
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "userId": 1,
  "title": "Hello",
  "content": "Nice to meet you"
}
